# @name login
POST http://127.0.0.1:{{$dotenv APP_PORT}}/api/project/login HTTP/1.1
content-type: application/json

{
    "userName": "admin",
    "userPassword": "123456"
}

###

POST http://127.0.0.1:{{$dotenv APP_PORT}}/api/admin-sqlite/get-table-schema HTTP/1.1
content-type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
    "tableName": "user"
}