services:
  app:
    image: lsby-playground-ts-service-dev
    build:
      context: ../../
      dockerfile: ./deploy/development/dockerfile
    ports:
      - 3000:3000
    env_file:
      - ../../.env/.env.development.web
    restart: always
    volumes:
      - ../../db:/opt/app/db
    logging:
      options:
        max-size: '100m'
        max-file: '5'
