services:
  app:
    image: lsby-playground-ts-service-prod
    build:
      context: ../../
      dockerfile: ./deploy/production/dockerfile
    ports:
      - 80:80
    env_file:
      - ../../.env/.env.production.web
    restart: always
    volumes:
      - ../../db:/opt/app/db
    logging:
      options:
        max-size: '100m'
        max-file: '5'
